# Generated by Django 4.2.7 on 2023-12-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
